// Generated by IR2Vec. DO NOT EDIT!
// This file defines the base class for vocabulary and the factory 
// for creating vocabulary instances used by IR2Vec.
// clang-format off

#include <memory>
#include "Vocabulary.h"

#include "Vocabulary100D.h"
#include "Vocabulary300D.h"
#include "Vocabulary75D.h"

namespace IR2Vec {

std::unique_ptr<VocabularyBase> VocabularyFactory::createVocabulary(unsigned dim) {
    switch (dim) {
        case 100:
            return std::make_unique<Vocabulary100D>();
        case 300:
            return std::make_unique<Vocabulary300D>();
        case 75:
            return std::make_unique<Vocabulary75D>();
        default:
            throw std::invalid_argument("Invalid dimension for vocabulary creation.");
    }
}
} // namespace IR2Vec

