var searchData=
[
  ['table_20of_20contents_0',['Table Of Contents',['../md_README.html#autotoc_md31',1,'']]],
  ['taken_1',['Time Taken',['..//github/workspace/experiments/README.md#autotoc_md28',1,'']]],
  ['tensorboard_20tracking_2',['TensorBoard Tracking',['..//github/workspace/seed_embeddings/README.md#autotoc_md70',1,'']]],
  ['test_20oracle_3',['Generate Test Oracle',['../md_docs_2version__upgrade__process.html#autotoc_md14',1,'']]],
  ['testdataloader_4',['TestDataLoader',['../classOpenKE_1_1data_1_1TestDataLoader_1_1TestDataLoader.html',1,'OpenKE::data::TestDataLoader']]],
  ['testdatasampler_5',['TestDataSampler',['../classOpenKE_1_1data_1_1TestDataLoader_1_1TestDataSampler.html',1,'OpenKE::data::TestDataLoader']]],
  ['tester_6',['Tester',['../classOpenKE_1_1config_1_1Tester_1_1Tester.html',1,'OpenKE::config::Tester']]],
  ['the_20data_7',['the data',['../md_docs_2comPile.html#autotoc_md3',1,'Preprocesing the data'],['../md_docs_2version__upgrade__process.html#autotoc_md12',1,'Preprocesing the data']]],
  ['the_20ir2vec_20binary_8',['Compile the IR2Vec binary',['../md_docs_2version__upgrade__process.html#autotoc_md9',1,'']]],
  ['the_20triplets_9',['the triplets',['..//github/workspace/seed_embeddings/README.md#autotoc_md67',1,'Preprocessing the triplets'],['..//github/workspace/seed_embeddings/README.md#autotoc_md63',1,'Steps to collect the triplets']]],
  ['thread_20coarsening_10',['Thread Coarsening',['..//github/workspace/experiments/README.md#autotoc_md24',1,'']]],
  ['time_20taken_11',['Time Taken',['..//github/workspace/experiments/README.md#autotoc_md28',1,'']]],
  ['to_20collect_20the_20triplets_12',['Steps to collect the triplets',['..//github/workspace/seed_embeddings/README.md#autotoc_md63',1,'']]],
  ['to_20generate_20embeddings_13',['Training TransE to generate embeddings',['..//github/workspace/seed_embeddings/README.md#autotoc_md68',1,'']]],
  ['to_20generate_20seed_20embedding_20vocabulary_14',['Files used to generate Seed Embedding Vocabulary',['..//github/workspace/seed_embeddings/README.md#autotoc_md64',1,'']]],
  ['to_20generate_20seed_20embedding_20vocabulary_15',['Step 3: Training TransE to generate seed embedding vocabulary',['..//github/workspace/seed_embeddings/README.md#autotoc_md65',1,'']]],
  ['to_20run_16',['to Run',['..//github/workspace/experiments/README.md#autotoc_md22',1,'Steps to Run'],['..//github/workspace/experiments/README.md#autotoc_md25',1,'Steps to Run']]],
  ['tracking_17',['TensorBoard Tracking',['..//github/workspace/seed_embeddings/README.md#autotoc_md70',1,'']]],
  ['train_20ids_18',['Train IDs',['../md_docs_2comPile.html#autotoc_md4',1,'']]],
  ['traindataloader_19',['TrainDataLoader',['../classOpenKE_1_1data_1_1TrainDataLoader_1_1TrainDataLoader.html',1,'OpenKE::data::TrainDataLoader']]],
  ['traindatasampler_20',['TrainDataSampler',['../classOpenKE_1_1data_1_1TrainDataLoader_1_1TrainDataSampler.html',1,'OpenKE::data::TrainDataLoader']]],
  ['trainer_21',['Trainer',['../classOpenKE_1_1config_1_1Trainer_1_1Trainer.html',1,'OpenKE::config::Trainer']]],
  ['training_22',['Training',['../md_docs_2version__upgrade__process.html#autotoc_md13',1,'']]],
  ['training_23',['training',['../md_docs_2comPile.html#autotoc_md0',1,'# Generating .ll files for re-training.'],['../md_docs_2version__upgrade__process.html#autotoc_md10',1,'Generating .ll files for re-training.']]],
  ['training_20transe_20to_20generate_20embeddings_24',['Training TransE to generate embeddings',['..//github/workspace/seed_embeddings/README.md#autotoc_md68',1,'']]],
  ['training_20transe_20to_20generate_20seed_20embedding_20vocabulary_25',['Step 3: Training TransE to generate seed embedding vocabulary',['..//github/workspace/seed_embeddings/README.md#autotoc_md65',1,'']]],
  ['training_20triplets_26',['Training Triplets',['../md_docs_2comPile.html#autotoc_md1',1,'Generating Training Triplets'],['../md_docs_2version__upgrade__process.html#autotoc_md11',1,'Generating Training Triplets']]],
  ['transd_27',['TransD',['../classOpenKE_1_1module_1_1model_1_1TransD_1_1TransD.html',1,'OpenKE::module::model::TransD']]],
  ['transe_28',['TransE',['../classOpenKE_1_1module_1_1model_1_1TransE_1_1TransE.html',1,'OpenKE::module::model::TransE']]],
  ['transe_20to_20generate_20embeddings_29',['Training TransE to generate embeddings',['..//github/workspace/seed_embeddings/README.md#autotoc_md68',1,'']]],
  ['transe_20to_20generate_20seed_20embedding_20vocabulary_30',['Step 3: Training TransE to generate seed embedding vocabulary',['..//github/workspace/seed_embeddings/README.md#autotoc_md65',1,'']]],
  ['transh_31',['TransH',['../classOpenKE_1_1module_1_1model_1_1TransH_1_1TransH.html',1,'OpenKE::module::model::TransH']]],
  ['transr_32',['TransR',['../classOpenKE_1_1module_1_1model_1_1TransR_1_1TransR.html',1,'OpenKE::module::model::TransR']]],
  ['triple_33',['Triple',['../structTriple.html',1,'']]],
  ['triplets_34',['Triplets',['../md_docs_2comPile.html#autotoc_md1',1,'Generating Training Triplets'],['../md_docs_2version__upgrade__process.html#autotoc_md11',1,'Generating Training Triplets'],['..//github/workspace/seed_embeddings/README.md#autotoc_md62',1,'Step 2: Generating Triplets']]],
  ['triplets_35',['triplets',['..//github/workspace/seed_embeddings/README.md#autotoc_md67',1,'Preprocessing the triplets'],['..//github/workspace/seed_embeddings/README.md#autotoc_md63',1,'Steps to collect the triplets']]],
  ['triplets_20txt_36',['Breaking triplets.txt',['../md_docs_2comPile.html#autotoc_md2',1,'']]],
  ['tt_37',['Step 1: Building &lt;tt&gt;ir2vec&lt;/tt&gt;',['..//github/workspace/seed_embeddings/README.md#autotoc_md61',1,'']]],
  ['tt_20ir2vec_20tt_38',['Step 1: Building &lt;tt&gt;ir2vec&lt;/tt&gt;',['..//github/workspace/seed_embeddings/README.md#autotoc_md61',1,'']]],
  ['txt_39',['Breaking triplets.txt',['../md_docs_2comPile.html#autotoc_md2',1,'']]]
];
