var searchData=
[
  ['table_20of_20contents_0',['Table Of Contents',['../md_README.html#autotoc_md26',1,'']]],
  ['taken_1',['Time Taken',['../md_experiments_2README.html#autotoc_md23',1,'']]],
  ['tensorboard_20tracking_2',['TensorBoard Tracking',['../md_seed__embeddings_2README.html#autotoc_md65',1,'']]],
  ['test_20oracle_3',['Generate Test Oracle',['../md_docs_2version__upgrade__process.html#autotoc_md9',1,'']]],
  ['test_20suite_4',['Test suite',['../md_src_2test-suite_2README.html',1,'']]],
  ['testdataloader_5',['TestDataLoader',['../classOpenKE_1_1data_1_1TestDataLoader_1_1TestDataLoader.html',1,'OpenKE::data::TestDataLoader']]],
  ['testdatasampler_6',['TestDataSampler',['../classOpenKE_1_1data_1_1TestDataLoader_1_1TestDataSampler.html',1,'OpenKE::data::TestDataLoader']]],
  ['tester_7',['Tester',['../classOpenKE_1_1config_1_1Tester_1_1Tester.html',1,'OpenKE::config::Tester']]],
  ['the_20data_8',['Preprocesing the data',['../md_docs_2version__upgrade__process.html#autotoc_md7',1,'']]],
  ['the_20ir2vec_20binary_9',['Compile the IR2Vec binary',['../md_docs_2version__upgrade__process.html#autotoc_md4',1,'']]],
  ['the_20triplets_10',['the triplets',['../md_seed__embeddings_2README.html#autotoc_md62',1,'Preprocessing the triplets'],['../md_seed__embeddings_2README.html#autotoc_md58',1,'Steps to collect the triplets']]],
  ['thread_20coarsening_11',['Thread Coarsening',['../md_experiments_2README.html#autotoc_md19',1,'']]],
  ['time_20taken_12',['Time Taken',['../md_experiments_2README.html#autotoc_md23',1,'']]],
  ['to_20collect_20the_20triplets_13',['Steps to collect the triplets',['../md_seed__embeddings_2README.html#autotoc_md58',1,'']]],
  ['to_20generate_20embeddings_14',['Training TransE to generate embeddings',['../md_seed__embeddings_2README.html#autotoc_md63',1,'']]],
  ['to_20generate_20seed_20embedding_20vocabulary_15',['Files used to generate Seed Embedding Vocabulary',['../md_seed__embeddings_2README.html#autotoc_md59',1,'']]],
  ['to_20generate_20seed_20embedding_20vocabulary_16',['Step 3: Training TransE to generate seed embedding vocabulary',['../md_seed__embeddings_2README.html#autotoc_md60',1,'']]],
  ['to_20run_17',['to Run',['../md_experiments_2README.html#autotoc_md17',1,'Steps to Run'],['../md_experiments_2README.html#autotoc_md20',1,'Steps to Run']]],
  ['tracking_18',['TensorBoard Tracking',['../md_seed__embeddings_2README.html#autotoc_md65',1,'']]],
  ['traindataloader_19',['TrainDataLoader',['../classOpenKE_1_1data_1_1TrainDataLoader_1_1TrainDataLoader.html',1,'OpenKE::data::TrainDataLoader']]],
  ['traindatasampler_20',['TrainDataSampler',['../classOpenKE_1_1data_1_1TrainDataLoader_1_1TrainDataSampler.html',1,'OpenKE::data::TrainDataLoader']]],
  ['trainer_21',['Trainer',['../classOpenKE_1_1config_1_1Trainer_1_1Trainer.html',1,'OpenKE::config::Trainer']]],
  ['training_22',['Training',['../md_docs_2version__upgrade__process.html#autotoc_md8',1,'']]],
  ['training_23',['Generating .ll files for re-training.',['../md_docs_2version__upgrade__process.html#autotoc_md5',1,'']]],
  ['training_20transe_20to_20generate_20embeddings_24',['Training TransE to generate embeddings',['../md_seed__embeddings_2README.html#autotoc_md63',1,'']]],
  ['training_20transe_20to_20generate_20seed_20embedding_20vocabulary_25',['Step 3: Training TransE to generate seed embedding vocabulary',['../md_seed__embeddings_2README.html#autotoc_md60',1,'']]],
  ['training_20triplets_26',['Generating Training Triplets',['../md_docs_2version__upgrade__process.html#autotoc_md6',1,'']]],
  ['transd_27',['TransD',['../classOpenKE_1_1module_1_1model_1_1TransD_1_1TransD.html',1,'OpenKE::module::model::TransD']]],
  ['transe_28',['TransE',['../classOpenKE_1_1module_1_1model_1_1TransE_1_1TransE.html',1,'OpenKE::module::model::TransE']]],
  ['transe_20to_20generate_20embeddings_29',['Training TransE to generate embeddings',['../md_seed__embeddings_2README.html#autotoc_md63',1,'']]],
  ['transe_20to_20generate_20seed_20embedding_20vocabulary_30',['Step 3: Training TransE to generate seed embedding vocabulary',['../md_seed__embeddings_2README.html#autotoc_md60',1,'']]],
  ['transh_31',['TransH',['../classOpenKE_1_1module_1_1model_1_1TransH_1_1TransH.html',1,'OpenKE::module::model::TransH']]],
  ['transr_32',['TransR',['../classOpenKE_1_1module_1_1model_1_1TransR_1_1TransR.html',1,'OpenKE::module::model::TransR']]],
  ['triple_33',['Triple',['../structTriple.html',1,'']]],
  ['triplets_34',['Triplets',['../md_docs_2version__upgrade__process.html#autotoc_md6',1,'Generating Training Triplets'],['../md_seed__embeddings_2README.html#autotoc_md57',1,'Step 2: Generating Triplets']]],
  ['triplets_35',['triplets',['../md_seed__embeddings_2README.html#autotoc_md62',1,'Preprocessing the triplets'],['../md_seed__embeddings_2README.html#autotoc_md58',1,'Steps to collect the triplets']]],
  ['tt_36',['Step 1: Building &lt;tt&gt;ir2vec&lt;/tt&gt;',['../md_seed__embeddings_2README.html#autotoc_md56',1,'']]],
  ['tt_20ir2vec_20tt_37',['Step 1: Building &lt;tt&gt;ir2vec&lt;/tt&gt;',['../md_seed__embeddings_2README.html#autotoc_md56',1,'']]]
];
