// Generated by IR2Vec. DO NOT EDIT!
// This file defines the base class for vocabulary and the factory 
// for creating vocabulary instances used by IR2Vec.
// clang-format off

#ifndef __VOCABULARY_H__
#define __VOCABULARY_H__

#include <map>
#include <string>
#include <vector>
#include <memory>
#include <stdexcept> // For std::invalid_argument
namespace IR2Vec {

using Vector = std::vector<double>;

class VocabularyBase {
public:
    virtual ~VocabularyBase() {}
    virtual const std::map<std::string, IR2Vec::Vector>& getVocabulary() const = 0;
};

class VocabularyFactory {
public:
    static std::unique_ptr<VocabularyBase> createVocabulary(unsigned dim);
};

} // namespace IR2Vec

#endif // __VOCABULARY_H__
